### ISSUE TITLE
Working master branch again 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-services-box#15]
Diverged since building, difficult to run current branch. Recent work work last sprint has made it easier to wire up some services in services box, should not be far from having an easy to user master branch (vs just locally working repo right now)

**Comment by oed** [comment]
Make sure that the ipfs config for 3box-js does not connect to the websocket star node on p2p.3box.io.

**Comment by michaelsena** [comment]
Closing, reflected in other stories
